### ISSUE TITLE
Android Studio  build fail

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/matrix-android-sdk#115]
Executing tasks: [:matrix-sdk:generateDebugSources, :matrix-sdk:mockableAndroidJar, :matrix-sdk:prepareDebugUnitTestDependencies, :matrix-sdk:generateDebugAndroidTestSources, :matrix-sdk:compileDebugSources, :matrix-sdk:compileDebugUnitTestSources, :matrix-sdk:compileDebugAndroidTestSources]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:matrix-sdk:preBuild UP-TO-DATE
:matrix-sdk:preDebugBuild UP-TO-DATE
:matrix-sdk:checkDebugManifest
:matrix-sdk:preDebugAndroidTestBuild UP-TO-DATE
:matrix-sdk:preDebugUnitTestBuild UP-TO-DATE
:matrix-sdk:preReleaseBuild UP-TO-DATE
:matrix-sdk:preReleaseUnitTestBuild UP-TO-DATE
:matrix-sdk:prepareComAndroidSupportAppcompatV72103Library UP-TO-DATE
:matrix-sdk:prepareComAndroidSupportSupportV42103Library UP-TO-DATE
:matrix-sdk:prepareIoPristineLibjingle9690Library UP-TO-DATE
:matrix-sdk:prepareOlmSdkLibrary UP-TO-DATE
:matrix-sdk:prepareDebugDependencies
:matrix-sdk:compileDebugAidl UP-TO-DATE
:matrix-sdk:compileDebugRenderscript UP-TO-DATE
:matrix-sdk:generateDebugBuildConfig UP-TO-DATE
:matrix-sdk:mergeDebugShaders UP-TO-DATE
:matrix-sdk:compileDebugShaders UP-TO-DATE
:matrix-sdk:generateDebugAssets UP-TO-DATE
:matrix-sdk:mergeDebugAssets UP-TO-DATE
:matrix-sdk:generateDebugResValues UP-TO-DATE
:matrix-sdk:generateDebugResources UP-TO-DATE
:matrix-sdk:mergeDebugResources UP-TO-DATE
:matrix-sdk:processDebugManifest UP-TO-DATE
:matrix-sdk:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':matrix-sdk:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\wangjha\AppData\Local\Android\Sdk\build-tools\21.0.0\aapt.exe'' finished with non-zero exit value -1073741819

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.269 secs

The AS is the latest version.

**Comment by ylecollen** [comment]
Use the build tools 21.0.2 on Windows environment.

**Comment by wjhtinger** [comment]
It works, thanks.
