### ISSUE TITLE
Unnecessary application tag in SDK manifest

### ISSUE THREAD

**Issue by Rugvip** [matrix-org/matrix-android-sdk#12]
The `application` tag in the sdk manifest adds attributes that collide with applications that it's included in, e.g.

```
Error:(9, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:9:9
  	is also present at test:matrix-sdk:unspecified:15:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:7:5 to override
````

Afaik the application tag doesn't really serve any purpose and could be removed

**Comment by ylecollen** [comment]
It has been fixed when the application and the SDK have been splitted in two GIT repositories.

**Comment by ylecollen** [comment]
1 - It has been fixed when the application and the SDK have been splitted in two GIT repositories.
2 - The application tag is required to run the robolectric tests. The robolectric testrunner could be overriden but it is quite unuseful after the projects split.
