### ISSUE TITLE
LoginApiClient class not exist

### ISSUE THREAD

**Issue by JhetoX** [matrix-org/matrix-android-sdk#120]
To log in, use an instance of the login API client.

new LoginApiClient("https://matrix.org").loginWithPassword("user", "password", callback);

Where i can found this class ?

maybe need add this class on the this package "org.matrix.androidsdk.rest.client"

public class LoginApiClient extends LoginRestClient {

    public LoginApiClient(String uri){
        super(new HomeserverConnectionConfig(Uri.parse(uri)));
    }

    public HomeserverConnectionConfig getConfig() {
        return mHsConfig;
    }
}

**Comment by ylecollen** [comment]
Have a look on the project https://github.com/vector-im/riot-android : this application uses the matrix SDK.
