### ISSUE TITLE
"olm-sdk" not found on Android Studio 2.2

### ISSUE THREAD

**Issue by JhetoX** [matrix-org/matrix-android-sdk#121]
i found the solution:

import "olm-sdk"

comment on the sdk:

//compile(name: 'olm-sdk', ext: 'aar')
//flatDir {dir 'libs'}

and imports "'olm-sdk'" as module on the sdk:

compile project(':olm-sdk')

and import the sdk as module on you app:

compile project(':matrix-sdk')

**Comment by ylecollen** [comment]
This trick was already commented on the application.

Matrix SDK is compiled as a lib.

In the vector project, you have to uncomment some lines in settings.gradle and build.gradle.
