### ISSUE TITLE
Update robolectric plugin

### ISSUE THREAD

**Issue by Rugvip** [matrix-org/matrix-android-sdk#13]
When importing the sdk module into another project the gradle sync fails with the following error if using robolectric-gradle-plugin 0.14.0
```
Error:(12, 0) Cannot add a configuration with name 'testCompile' as a configuration with that name already exists.
```

Upgrading to robolectric-gradle-plugin 1.0.1 solves the issue. The plugin id is changed from `robolectric` to `org.robolectric` when upgrading.

**Comment by ylecollen** [comment]
Tthe SDK is now split out from the application (you just need to import the aar file to your project).
