### ISSUE TITLE
can this be used as a java sdk (without android)

### ISSUE THREAD

**Issue by komatr** [matrix-org/matrix-android-sdk#193]
hi, I've been working on a matrix client for the desktop. It's inspired by https://github.com/UprootLabs/unplug and written in kotlin/java.
i used retrofit to interact with the rest api, then i discovered this sdk
can i use it? please give me some pointers

**Comment by ylecollen** [comment]
i never tested it with java environment. Many things could be reused so please create branch for this       sdk to include the java sdk. I would be happy to add jsk support.

**Comment by MrCustomizer** [comment]
I came here with the same idea in mind. After a first look at the source code, I was a little bit surprised to see Fragments and Views in the source code. From the description of this project ("The Matrix SDK for Android wraps the Matrix REST API calls in asynchronous Java methods and provides basic structures for storing and handling data.") I would have only expected backend code. 

@ylecollen Did I understand you correctly, that you are proposing to create a separate branch, in which all the Android stuff is removed? I would be willing to spend some time on this. Perhaps I will create such a branch. Could you elaborate on what you mean by "I would be happy to add jsk support?".

**Comment by ylecollen** [comment]
@MrCustomizer 
The matrix SDK has been cleaned : only 2 fragments and few views are left.
They have been included to provide the minimum UI items to manage messages list.

 We never thought to support all the java platforms with this SDK : it was only design for the android platforms (it was the same for the IOS SDK which was only IOS compliant before being able to run on MacOs).

It would be nice to have a jar file for all the java platforms  + aar dedicated to android.
But, the call libs are only compiled for android by now so it is not so easy to have the java ones;

"I would be happy to add jsk support" -> I would be happy to add jdk (java) support".

**Comment by ylecollen** [comment]
Guys, 

your should join "https://riot.im/develop/#/room/#riot-android:matrix.org".
i did not see your questions here because more of them are asked in the Riot git (https://github.com/vector-im/riot-android)

**Comment by MrCustomizer** [comment]
Oh, that's interesting news. Though lately, I've been focusing my attention on https://github.com/kamax-io/matrix-java-sdk as I wouldn't have thought removing the Android dependencies would be a task which could be accomplished so easily. That SDK is still very basic, but as I already have invested significant time in improving this SDK and as I have even begun writing a client based on it, I will stay on this path for now.

**Comment by bmarty** [comment]
The answer is no, there are other pure Java SDK. This one will stay an Android SDK
