### ISSUE TITLE
Retrieve custom StateEvent

### ISSUE THREAD

**Issue by sammy44nts** [matrix-org/matrix-android-sdk#198]
Hello,

I'm using the Android SDK to interact with a Matrix server and I need to retrieve a custom StateEvent with a type like `com.corp.feature` but I didn't find a way to call:
[GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}](https://matrix.org/docs/spec/r0.0.0/client_server.html#get-matrix-client-r0-rooms-roomid-state-eventtype)
Is it me having trouble understanding how the SDK works?
Is this call not supposed to be implemented in `org.matrix.androidsdk.rest.api.RoomsApi`?

Best regards,

**Comment by ylecollen** [comment]
merged on develop
