### ISSUE TITLE
Room Creation: The new created room is not available while `success` callback is called 

### ISSUE THREAD

**Issue by giomfo** [matrix-org/matrix-android-sdk#206]
creating a room like this :
```
getMXSession().createRoom(name, topic, alias, 
RoomState.GUEST_ACCESS_FORBIDDEN, "private_chat", new 
ApiCallback<String>() {
           @Override
           public void onSuccess(String s) {
               Logger.in("Success room created  id " + s);

                getRooms() // triggers to another thread the get of 
room's list.

                 }
```

The callback success is correctly called.  So my app requests for the 
rooms list - (from another thread), the freshly created room is not 
within the list. I made the test to request the list again few seconds 
after, the room is in the list.

The point is, I do not receive any others event  that indicate the room 
is fully created and available within the list. (I miss a listener ?). 
My feeling is that the room has been correctly created and exists to 
server, but become available locally in the list  at next sync 
operation. Is this normal ?

**Comment by ylecollen** [comment]
When onSuccess is called, the room is created in all the cases.

https://github.com/matrix-org/matrix-android-sdk/blob/master/matrix-sdk/src/main/java/org/matrix/androidsdk/MXSession.java#L1225

The callback should be called when the room is initialised i.e the members list and other infos are defined.

**Comment by ylecollen** [comment]
It seems working on my side
mSession.getDataHandler().getStore().getRooms() includes it

To track rooms creation, there is a global listener.
 mSession.getDataHandler().addListener(IMXEventListener listener);
There is a callback   "void onNewRoom(String roomId);"
