### ISSUE TITLE
Firebase login

### ISSUE THREAD

**Issue by vishnubenny** [matrix-org/matrix-android-sdk#212]
Hi,

Can I use firebase login (firebase auth) with matrix sdk login?
I have done firebase login and I have firebase user. How do you I connect my firebase user with matrix-sdk?

**Comment by ylecollen** [comment]
@vishnubenny 
Do you talk about the firebase push management ?

**Comment by lekshmis** [comment]
@ylecollen 
Not about firebase push management. Instead of registering a user with username, password and email, can I use firebase user property to authenticate into matrix?

**Comment by vishnubenny** [comment]
@ylecollen
Not about firebase push management. Instead of registering a user with username, password and email, can I use firebase user property to authenticate into matrix?

**Comment by ylecollen** [comment]
@vishnubenny 
i don't think there is a server API to manage it.

**Comment by vishnubenny** [comment]
@ylecollen 
Will you update matrix sdk in coming versions for firebase login support?
My question is that,
instead of registering with username, email and password can I user google auth for registering?
Is there any way to register an email (auth done by google-firebase) without password into matrix sdk?

**Comment by mrtshoot** [comment]
@ylecollen
