### ISSUE TITLE
No sample app

### ISSUE THREAD

**Issue by dmp5** [matrix-org/matrix-android-sdk#216]
The readme states as following:

> It is an Android Studio (gradle) project containing two modules:
> - sdk - The SDK
> - app - The sample app using the SDK

There is no sample app in the current master branch, can you please point out to its location (if any)?

**Comment by dmp5** [comment]
Follow up, should [https://github.com/vector-im/riot-android](Riot) app serve as an example app?

**Comment by ylecollen** [comment]
@dmp5 
Right, Riot is the sample app.

**Comment by ylecollen** [comment]
i updated the Readme file
