### ISSUE TITLE
File uploads with file name containing a path

### ISSUE THREAD

**Issue by christarazi** [matrix-org/matrix-android-sdk#228]
Different clients may choose to put the entire file path in `m.body` when uploading files, which is used as the default file name in [`saveMedia`](https://github.com/matrix-org/matrix-android-sdk/blob/49fcd0c3790e293f62bfb84773325725c53b9f5c/matrix-sdk/src/main/java/org/matrix/androidsdk/db/MXMediasCache.java#L433). A toast appears with an error: `No such file or directory` when trying to save the file. 

Perhaps detecting if a file name contains a path, and just trimming it to contain only the name would fix the issue. I thought I'd inform you guys here to get your opinion instead of creating a PR immediately.

**Comment by ylecollen** [comment]
@christarazi 
The m.body sets to the filename is the same behaviour on all the plaforms.
This body is the value displayed in the recents list for example.

It would be weird to have "C:\users\..." on an android device.

Moreover, the windows pathes won't be detected as valid ones on other platforms.
On IOS, you don't have the full path.

Even on android platforms, the path might be different.

**Comment by christarazi** [comment]
I think we might have a misunderstanding.

I am suggesting to have Riot look at `m.body`, and if it contains a file path (anything other than just a filename), then when saving files, trim `m.body` to only the filename.

For example:

`/path/to/file` -> `file`
`c:\path\to\file` -> `file`

The reason is because some clients choose to put the entire file path in `m.body`, which is not explicitly disallowed in the spec. When using Riot to download them, it will try to save the file to the path specified in `m.body`, which causes Riot to fail and display an error.

**Comment by Matrixcoffee** [comment]
Riot should at the very least sanitize the filename it is trying to save to.

**Comment by christarazi** [comment]
Closing as vector-im/riot-android#2019 has been merged.
