### ISSUE TITLE
Backward Compatibility issue

### ISSUE THREAD

**Issue by winsontan520** [matrix-org/matrix-android-sdk#23]
Found a backward compatibility issue for SDK
```
Error:Execution failed for task ':dating:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/admin/Softwares/adt-bundle-mac-x86_64/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1
```
And found that is due to my project is using appcompat v7:20.0.0 meanwhile the library 
Matrix SDK is using gradle dependency compile 'com.android.support:appcompat-v7:21.0.0'

First, in order to use Matrix SDK i need to upgrade current project to support v21, this doesn't make sense as to test Matrix SDK integration, we would need to update project to support v21 which cause a lot time and efforts.

Secondly, it is weird that the SDK contain the UI stuff like layout using appcompat style, adapter, fragment. I don't see a reason these codes should handle in sdk instead in app.

Lastly, it would best the sdk can support gradle dependency too.

Just my2cent. Thanks for the contribution!

**Comment by ylecollen** [comment]
Hello winsontan520, 

First, i would like to thank you for your comments. Any comments are always welcome.

1 - The project has been split (SDK and application). The appcompat issue should have been fixed (the latest client also suppports the lolipop UI items).

2 - The SDK contains UI stuff to simplify the application development. They are inheritable so the application UI items are smaller (it was a requirement).
     It could be moved into another lib later.

3 - The library will support gradle denpency when it will become more stable and safer. It is planned.
