### ISSUE TITLE
Cannot set the value of read only property 'Output File'

### ISSUE THREAD

**Issue by souravmunjal** [matrix-org/matrix-android-sdk#238]
I tried to add module of matrix in my app it is the following error

Error:(80, 0) Cannot set the value of read-only property 'outputFile' for object of type com.android.build.gradle.internal.api.LibraryVariantOutputImpl.
![image](https://user-images.githubusercontent.com/30770269/36733841-e251f5e2-1bf7-11e8-931e-ca5f7aa40009.png)

**Comment by bmarty** [comment]
Build tools has been updated, this issue should be fixed with the last version of the SDK

**Comment by bmarty** [comment]
ok, fixed
