### ISSUE TITLE
Matrix identifiers regexps: Support homeservers with port in all regexps

### ISSUE THREAD

**Issue by manuroe** [matrix-org/matrix-android-sdk#239]
Only userId via [MATRIX_USER_IDENTIFIER_REGEX](https://github.com/matrix-org/matrix-android-sdk/blob/634d7de85e640d650dbc8facf37e40bef6cd0d51/matrix-sdk/src/main/java/org/matrix/androidsdk/MXSession.java#L170) supports homeservers domains with a port.
Regexps for roomId, eventId, etc should do too.

(iOS code for reference: https://github.com/matrix-org/matrix-ios-sdk/pull/459)

**Comment by bmarty** [comment]
@manuroe , this is strange, this older commit (Jul 31, 2017) does this: c1ccc0bce14ef3236888e78b6030dc8b5208cff3
I think we can close this issue then?

**Comment by manuroe** [comment]
Yes. No reason to keep this issue.
