### ISSUE TITLE
Android 5.1.1 not compatible

### ISSUE THREAD

**Issue by skryking** [matrix-org/matrix-android-sdk#24]
Tried to download the app from the play store and it seems it hasn't caught up with the latest version of android.  Is there anything stopping me from just cloning the repo and bumping the target sdk up?  I'm on a nexus 7 if it matters.

**Comment by ara4n** [comment]
Weird. We should be supporting newer Androids by default, i'd have hoped. Clone + bump + build should work fine (modulo GCM, which I assume needs an official build & our keys to work).

**Comment by skryking** [comment]
Play store said it wasn't compatible with my device and wouldn't even let me install it.

**Comment by ylecollen** [comment]
skyring,

It should be fixed in the next release.

The application should not be installed in your nexus 7 because there were a TELEPHONY hardware requirement. Indeed the application could send a SMS to invite another user to use console.

**Comment by oddvar** [comment]
Hiya skryking,

the playstore build has now been updated and you should be able to install the app from https://play.google.com/store/apps/details?id=org.matrix.androidsdk.alpha - thanks for raising this issue!
