### ISSUE TITLE
Unable to use via Jitpack

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/matrix-android-sdk#241]
Hi I tried to use this via Jitpack but I get the following error from Android Studio:

```
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.matrix-org:matrix-android-sdk:v0.9.0.

Could not resolve com.github.matrix-org:matrix-android-sdk:v0.9.0.
Required by:
    project :app
 > Could not resolve com.github.matrix-org:matrix-android-sdk:v0.9.0.
    > Could not parse POM https://jitpack.io/com/github/matrix-org/matrix-android-sdk/v0.9.0/matrix-android-sdk-v0.9.0.pom
          > Missing required attribute: dependency groupId
```

Is there a way that can be fixed on the repo size or someone here with tips to fix it on my side?

**Comment by MTRNord** [comment]
My problem is propably related to this: https://jitpack.io/docs/#building-with-jitpack

**Comment by MTRNord** [comment]
Oh it is a combination of the missing "android-maven-gradle-plugin" plugin and having this

```
compile(name: 'olm-sdk', ext: 'aar')

    // replace the compile 'io.pristine:libjingle:9690@aar'
compile(name: 'react-native-webrtc', ext: 'aar')
```

**Comment by bmarty** [comment]
It's seems to work fine today, and I'm using it for Riot \o/
https://jitpack.io/#matrix-org/matrix-android-sdk/
