### ISSUE TITLE
Latest version , can not build under Android Studio

### ISSUE THREAD

**Issue by begee** [matrix-org/matrix-android-sdk#28]
details
Error:Execution failed for task ':matrix-sdk:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\android-sdk\build-tools\21.0.0\aapt.exe'' finished with non-zero exit value -1073741819

I have found some explains about the error  on Stackflow , but I don't find any resource which bring this error

**Comment by ylecollen** [comment]
begee,
We got such issues with android studio under Windows 7 environment. 

Could you try with     

compileSdkVersion 21
buildToolsVersion '21.1.2' 

It should fix your issue.

**Comment by mitchhentges** [comment]
Should be fixed by #35

**Comment by elpoisterio** [comment]
is it still having the problem ?

**Comment by raoudhaa** [comment]
i have the same error,
could any one help me to resolve it and thanks
![12874653_714569505352113_986474238_o](https://cloud.githubusercontent.com/assets/18017357/13970629/e28d7a52-f081-11e5-96cd-a8c2b5931dbb.jpg)
[](url)

**Comment by JhetoX** [comment]
I have this new error:
Error:Failed to resolve: :olm-sdk:

**Comment by fnc12** [comment]
sorry for stupid question but how do you add this nice lib to gradle script to include and build it within my app? Thanks

**Comment by ylecollen** [comment]
1- add a libs directory in your project
2- copy the required libs (have a look to the riot project to get all of them)
https://github.com/vector-im/riot-android
3- update your project gradle
https://github.com/vector-im/riot-android/blob/master/vector/build.gradle#L106
https://github.com/vector-im/riot-android/blob/master/vector/build.gradle#L159

**Comment by ylecollen** [comment]
@fnc12 
@ctin
@JhetoX 
See my answer
