### ISSUE TITLE
Bad formatting strings in ja translation

### ISSUE THREAD

**Issue by Limvot** [matrix-org/matrix-android-sdk#423]
https://github.com/matrix-org/matrix-android-sdk/blob/7fd0f2e847af402a19d9986a5da1c65c9044dd64/matrix-sdk/src/main/res/values-ja/strings.xml#L16 seems to be wrong (and the line below it) - I believe %14 was typed instead of %1$, causing my app to fail to build. I'm curious as to how Riot builds, as even downloading the version they ship causes my app to fail to build (unless I'm missing something cached somewhere, it's late so I could have missed something).

**Comment by bmarty** [comment]
Oh, yes, I do not understand why lint has let this happen.
I fix the issue (two occurences)
