### ISSUE TITLE
How to add translations within embeddedPages.welcomeUrl HTML file?

### ISSUE THREAD

**Issue by eMPee584** [matrix-org/matrix-android-sdk#461]
We have a customized welcome.html and have a few strings in there that we would like to provide translations for into another language. Is there any way (`<script>magic</script>`) to **add these translations from within that file** without modding `i18n/strings/X.json`, recompiling it into a bundle and overlaying it into the docker image we use?

**Comment by eMPee584** [comment]
Wait, this is the wrong SDK.. :smile: 
but matrix-react-sdk has issues disabled.. now what :thinking:

**Comment by t3chguy** [comment]
Riot-web collects react-sdk issues
