### ISSUE TITLE
android studio build fail

### ISSUE THREAD

**Issue by kingwap99** [matrix-org/matrix-android-sdk#479]
When I opened v0.9.2 in Android Studio 
I got this error message 

ERROR: Failed to resolve: com.github.matrix-org:matrix-android-sdk:v0.9.24

this issue happened in both win10 & macos with the updated android studio

**Comment by bmarty** [comment]
Yes, I'm on it. Jitpack takes time to build the lib, and unfortunately it has failed to build it. I'm try to request a rebuild.

https://jitpack.io/#matrix-org/matrix-android-sdk

**Comment by bmarty** [comment]
@kingwap99,
I've pushed a [hotfix](https://github.com/vector-im/riot-android/commit/3b053b699cedb95f065a9e5c5e0d399a7e8f500d) which fixes the pb, but Jitpack has sometimes difficulties to retrieve some dependencies...

**Comment by kingwap99** [comment]
@bmarty 
thanks, it works now.
