### ISSUE TITLE
Custom fields from content in sendEvent don't come in onEvent

### ISSUE THREAD

**Issue by closw** [matrix-org/matrix-android-sdk#515]
I create even as follows:
```
JsonParser parser = new JsonParser();
        JsonElement element = parser.parse("{" +
                "\"body\" : \"" + text + "\"," +
                "\"msgtype\" : \"m.text\"," +
                "\"mirrorIdKey\" : \"" + mirrorIdKey + "\"" +
                "}");
        JsonObject content = element.getAsJsonObject();
        Event event = new Event(Event.EVENT_TYPE_MESSAGE, content, myUserId, roomId);
```
and send it:
```
room.sendEvent(event, new SimpleApiCallback<Void>() {
            @Override
            public void onSuccess(Void aVoid) {
               //some logic
            }
        });
```

and my custom field "mirrorIdKey" don't come in interface method onEvent.
How I can get "mirrorIdKey" in "onEvent"?

**Comment by bmarty** [comment]
Hello @closw ,
I've fixed your issue in #526. Actually the custom fields was not sent. I've added a test to cover this case, which was not passing before the fix, and is passing after the fix :)
The release will be done once the PR is approved by the team.
Thanks for reporting this issue!
