### ISSUE TITLE
Build fails because of Olm dependency

### ISSUE THREAD

**Issue by hannojg** [matrix-org/matrix-android-sdk#537]
Hello, 

since yesterday we can’t get the sdk working in our projects. It fails due to this error:
![6D3855F7-CF9E-4345-968F-952C2E9C060D](https://user-images.githubusercontent.com/16821682/79067884-18841e00-7cc3-11ea-934b-9a40c1c2e830.jpeg)

Have there been any breaking changes? 
Thanks for your time.

**Comment by bmarty** [comment]
No, but sometimes Jitpack does not provide the Olm lib as expected. Trying again a few hours after solves the pb generally :/
