### ISSUE TITLE
compileSdkVersion 21 due to apache dependencies

### ISSUE THREAD

**Issue by Denis10** [matrix-org/matrix-android-sdk#87]
Can you please replace deprecated org.apache.http lib with HttpURLConnection to allow to increase sdk version?

**Comment by ylecollen** [comment]
You can fork our code if it is urgent.
I will merge your update.

**Comment by Denis10** [comment]
I did one
https://github.com/matrix-org/matrix-android-sdk/pull/92

**Comment by ylecollen** [comment]
I merged your UrlPostTask update but not your target updated : we have to keep the compliancy with the former console application.
